// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
	decimal "github.com/shopspring/decimal"
)

type PolymarketBook struct {
	ID         int64               `json:"id"`
	MarketID   string              `json:"market_id"`
	Question   string              `json:"question"`
	YesBid     decimal.NullDecimal `json:"yes_bid"`
	YesAsk     decimal.NullDecimal `json:"yes_ask"`
	NoBid      decimal.NullDecimal `json:"no_bid"`
	NoAsk      decimal.NullDecimal `json:"no_ask"`
	TsReceived pgtype.Timestamptz  `json:"ts_received"`
	RawPayload []byte              `json:"raw_payload"`
}

type PriceTick struct {
	ID         int64              `json:"id"`
	Exchange   string             `json:"exchange"`
	Symbol     string             `json:"symbol"`
	Price      decimal.Decimal    `json:"price"`
	TsExchange pgtype.Timestamptz `json:"ts_exchange"`
	TsReceived pgtype.Timestamptz `json:"ts_received"`
	RawPayload []byte             `json:"raw_payload"`
}

type Signal struct {
	ID           int64              `json:"id"`
	Symbol       string             `json:"symbol"`
	Direction    string             `json:"direction"`
	Magnitude    decimal.Decimal    `json:"magnitude"`
	WindowMs     int32              `json:"window_ms"`
	Confidence   decimal.Decimal    `json:"confidence"`
	DetectedAt   pgtype.Timestamptz `json:"detected_at"`
	Context      []byte             `json:"context"`
	ActionTaken  pgtype.Text        `json:"action_taken"`
	ActionReason pgtype.Text        `json:"action_reason"`
}

type Trade struct {
	ID              int64               `json:"id"`
	SignalID        pgtype.Int8         `json:"signal_id"`
	Mode            string              `json:"mode"`
	MarketID        string              `json:"market_id"`
	Side            string              `json:"side"`
	EntryPrice      decimal.Decimal     `json:"entry_price"`
	SizeUsd         decimal.Decimal     `json:"size_usd"`
	ExitPrice       decimal.NullDecimal `json:"exit_price"`
	PnlUsd          decimal.NullDecimal `json:"pnl_usd"`
	FeesUsd         decimal.NullDecimal `json:"fees_usd"`
	OpenedAt        pgtype.Timestamptz  `json:"opened_at"`
	ClosedAt        pgtype.Timestamptz  `json:"closed_at"`
	Status          string              `json:"status"`
	ExternalOrderID pgtype.Text         `json:"external_order_id"`
}
