// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	decimal "github.com/shopspring/decimal"
)

const countPriceTicksSince = `-- name: CountPriceTicksSince :one
SELECT count(*) FROM price_ticks
WHERE exchange = $1 AND ts_received >= $2
`

type CountPriceTicksSinceParams struct {
	Exchange   string             `json:"exchange"`
	TsReceived pgtype.Timestamptz `json:"ts_received"`
}

func (q *Queries) CountPriceTicksSince(ctx context.Context, arg CountPriceTicksSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPriceTicksSince, arg.Exchange, arg.TsReceived)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLatestPriceTick = `-- name: GetLatestPriceTick :one
SELECT id, exchange, symbol, price, ts_exchange, ts_received
FROM price_ticks
WHERE exchange = $1 AND symbol = $2
ORDER BY ts_exchange DESC
LIMIT 1
`

type GetLatestPriceTickParams struct {
	Exchange string `json:"exchange"`
	Symbol   string `json:"symbol"`
}

type GetLatestPriceTickRow struct {
	ID         int64              `json:"id"`
	Exchange   string             `json:"exchange"`
	Symbol     string             `json:"symbol"`
	Price      decimal.Decimal    `json:"price"`
	TsExchange pgtype.Timestamptz `json:"ts_exchange"`
	TsReceived pgtype.Timestamptz `json:"ts_received"`
}

func (q *Queries) GetLatestPriceTick(ctx context.Context, arg GetLatestPriceTickParams) (GetLatestPriceTickRow, error) {
	row := q.db.QueryRow(ctx, getLatestPriceTick, arg.Exchange, arg.Symbol)
	var i GetLatestPriceTickRow
	err := row.Scan(
		&i.ID,
		&i.Exchange,
		&i.Symbol,
		&i.Price,
		&i.TsExchange,
		&i.TsReceived,
	)
	return i, err
}

const insertPriceTick = `-- name: InsertPriceTick :one
INSERT INTO price_ticks (
  exchange, symbol, price, ts_exchange, raw_payload
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id
`

type InsertPriceTickParams struct {
	Exchange   string             `json:"exchange"`
	Symbol     string             `json:"symbol"`
	Price      decimal.Decimal    `json:"price"`
	TsExchange pgtype.Timestamptz `json:"ts_exchange"`
	RawPayload []byte             `json:"raw_payload"`
}

func (q *Queries) InsertPriceTick(ctx context.Context, arg InsertPriceTickParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertPriceTick,
		arg.Exchange,
		arg.Symbol,
		arg.Price,
		arg.TsExchange,
		arg.RawPayload,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
