// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	decimal "github.com/shopspring/decimal"
)

const countPolymarketBooksSince = `-- name: CountPolymarketBooksSince :one
SELECT count(*) FROM polymarket_books
WHERE market_id = $1 AND ts_received >= $2
`

type CountPolymarketBooksSinceParams struct {
	MarketID   string             `json:"market_id"`
	TsReceived pgtype.Timestamptz `json:"ts_received"`
}

func (q *Queries) CountPolymarketBooksSince(ctx context.Context, arg CountPolymarketBooksSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPolymarketBooksSince, arg.MarketID, arg.TsReceived)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPriceTicksSince = `-- name: CountPriceTicksSince :one
SELECT count(*) FROM price_ticks
WHERE exchange = $1 AND ts_received >= $2
`

type CountPriceTicksSinceParams struct {
	Exchange   string             `json:"exchange"`
	TsReceived pgtype.Timestamptz `json:"ts_received"`
}

func (q *Queries) CountPriceTicksSince(ctx context.Context, arg CountPriceTicksSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPriceTicksSince, arg.Exchange, arg.TsReceived)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLatestActiveMarket = `-- name: GetLatestActiveMarket :one
SELECT market_id, question, ts_received AS last_seen
FROM polymarket_books
WHERE ts_received >= $1
ORDER BY ts_received DESC
LIMIT 1
`

type GetLatestActiveMarketRow struct {
	MarketID string             `json:"market_id"`
	Question string             `json:"question"`
	LastSeen pgtype.Timestamptz `json:"last_seen"`
}

func (q *Queries) GetLatestActiveMarket(ctx context.Context, tsReceived pgtype.Timestamptz) (GetLatestActiveMarketRow, error) {
	row := q.db.QueryRow(ctx, getLatestActiveMarket, tsReceived)
	var i GetLatestActiveMarketRow
	err := row.Scan(&i.MarketID, &i.Question, &i.LastSeen)
	return i, err
}

const getLatestNoQuote = `-- name: GetLatestNoQuote :one
SELECT no_bid, no_ask, ts_received
FROM polymarket_books
WHERE market_id = $1 AND no_bid IS NOT NULL
ORDER BY ts_received DESC
LIMIT 1
`

type GetLatestNoQuoteRow struct {
	NoBid      decimal.NullDecimal `json:"no_bid"`
	NoAsk      decimal.NullDecimal `json:"no_ask"`
	TsReceived pgtype.Timestamptz  `json:"ts_received"`
}

func (q *Queries) GetLatestNoQuote(ctx context.Context, marketID string) (GetLatestNoQuoteRow, error) {
	row := q.db.QueryRow(ctx, getLatestNoQuote, marketID)
	var i GetLatestNoQuoteRow
	err := row.Scan(&i.NoBid, &i.NoAsk, &i.TsReceived)
	return i, err
}

const getLatestPriceTick = `-- name: GetLatestPriceTick :one
SELECT id, exchange, symbol, price, ts_exchange, ts_received
FROM price_ticks
WHERE exchange = $1 AND symbol = $2
ORDER BY ts_exchange DESC
LIMIT 1
`

type GetLatestPriceTickParams struct {
	Exchange string `json:"exchange"`
	Symbol   string `json:"symbol"`
}

type GetLatestPriceTickRow struct {
	ID         int64              `json:"id"`
	Exchange   string             `json:"exchange"`
	Symbol     string             `json:"symbol"`
	Price      decimal.Decimal    `json:"price"`
	TsExchange pgtype.Timestamptz `json:"ts_exchange"`
	TsReceived pgtype.Timestamptz `json:"ts_received"`
}

func (q *Queries) GetLatestPriceTick(ctx context.Context, arg GetLatestPriceTickParams) (GetLatestPriceTickRow, error) {
	row := q.db.QueryRow(ctx, getLatestPriceTick, arg.Exchange, arg.Symbol)
	var i GetLatestPriceTickRow
	err := row.Scan(
		&i.ID,
		&i.Exchange,
		&i.Symbol,
		&i.Price,
		&i.TsExchange,
		&i.TsReceived,
	)
	return i, err
}

const getLatestYesQuote = `-- name: GetLatestYesQuote :one
SELECT yes_bid, yes_ask, ts_received
FROM polymarket_books
WHERE market_id = $1 AND yes_bid IS NOT NULL
ORDER BY ts_received DESC
LIMIT 1
`

type GetLatestYesQuoteRow struct {
	YesBid     decimal.NullDecimal `json:"yes_bid"`
	YesAsk     decimal.NullDecimal `json:"yes_ask"`
	TsReceived pgtype.Timestamptz  `json:"ts_received"`
}

func (q *Queries) GetLatestYesQuote(ctx context.Context, marketID string) (GetLatestYesQuoteRow, error) {
	row := q.db.QueryRow(ctx, getLatestYesQuote, marketID)
	var i GetLatestYesQuoteRow
	err := row.Scan(&i.YesBid, &i.YesAsk, &i.TsReceived)
	return i, err
}

const insertPolymarketBook = `-- name: InsertPolymarketBook :one
INSERT INTO polymarket_books (
  market_id, question, yes_bid, yes_ask, no_bid, no_ask, raw_payload
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id
`

type InsertPolymarketBookParams struct {
	MarketID   string              `json:"market_id"`
	Question   string              `json:"question"`
	YesBid     decimal.NullDecimal `json:"yes_bid"`
	YesAsk     decimal.NullDecimal `json:"yes_ask"`
	NoBid      decimal.NullDecimal `json:"no_bid"`
	NoAsk      decimal.NullDecimal `json:"no_ask"`
	RawPayload []byte              `json:"raw_payload"`
}

func (q *Queries) InsertPolymarketBook(ctx context.Context, arg InsertPolymarketBookParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertPolymarketBook,
		arg.MarketID,
		arg.Question,
		arg.YesBid,
		arg.YesAsk,
		arg.NoBid,
		arg.NoAsk,
		arg.RawPayload,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPriceTick = `-- name: InsertPriceTick :one
INSERT INTO price_ticks (
  exchange, symbol, price, ts_exchange, raw_payload
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id
`

type InsertPriceTickParams struct {
	Exchange   string             `json:"exchange"`
	Symbol     string             `json:"symbol"`
	Price      decimal.Decimal    `json:"price"`
	TsExchange pgtype.Timestamptz `json:"ts_exchange"`
	RawPayload []byte             `json:"raw_payload"`
}

func (q *Queries) InsertPriceTick(ctx context.Context, arg InsertPriceTickParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertPriceTick,
		arg.Exchange,
		arg.Symbol,
		arg.Price,
		arg.TsExchange,
		arg.RawPayload,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSignal = `-- name: InsertSignal :one
INSERT INTO signals (
  symbol, direction, magnitude, window_ms, confidence, detected_at, context, action_taken, action_reason
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id
`

type InsertSignalParams struct {
	Symbol       string             `json:"symbol"`
	Direction    string             `json:"direction"`
	Magnitude    decimal.Decimal    `json:"magnitude"`
	WindowMs     int32              `json:"window_ms"`
	Confidence   decimal.Decimal    `json:"confidence"`
	DetectedAt   pgtype.Timestamptz `json:"detected_at"`
	Context      []byte             `json:"context"`
	ActionTaken  pgtype.Text        `json:"action_taken"`
	ActionReason pgtype.Text        `json:"action_reason"`
}

func (q *Queries) InsertSignal(ctx context.Context, arg InsertSignalParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertSignal,
		arg.Symbol,
		arg.Direction,
		arg.Magnitude,
		arg.WindowMs,
		arg.Confidence,
		arg.DetectedAt,
		arg.Context,
		arg.ActionTaken,
		arg.ActionReason,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listRecentSignals = `-- name: ListRecentSignals :many
SELECT id, symbol, direction, magnitude, window_ms, confidence, detected_at, context, action_taken, action_reason
FROM signals
ORDER BY detected_at DESC
LIMIT $1
`

func (q *Queries) ListRecentSignals(ctx context.Context, limit int32) ([]Signal, error) {
	rows, err := q.db.Query(ctx, listRecentSignals, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Signal{}
	for rows.Next() {
		var i Signal
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Direction,
			&i.Magnitude,
			&i.WindowMs,
			&i.Confidence,
			&i.DetectedAt,
			&i.Context,
			&i.ActionTaken,
			&i.ActionReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
